# coding: utf-8

"""
    Raven API

    This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: api@ravenapp.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import raven
from raven.api.raven_client import EventApi  # noqa: E501
from raven.rest import ApiException


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self):
        self.api = raven.api.event_api.EventApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send_bulk_event(self):
        """Test case for send_bulk_event

        sends the event in bulk to all the clients specified  # noqa: E501
        """
        pass

    def test_send_event(self):
        """Test case for send_event

        sends the event to the client specified  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
