# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.event_not_found_error_body import EventNotFoundErrorBody


class EventNotFoundError(ApiError):
    def __init__(self, body: EventNotFoundErrorBody):
        super().__init__(status_code=404, body=body)
