# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Platform(str, enum.Enum):
    ANDROID = "android"
    WEB = "web"
    IOS = "ios"

    def visit(
        self,
        android: typing.Callable[[], T_Result],
        web: typing.Callable[[], T_Result],
        ios: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Platform.ANDROID:
            return android()
        if self is Platform.WEB:
            return web()
        if self is Platform.IOS:
            return ios()
